# Site settings
title: Daniel Huber
email: mail@danielhuber.me
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog for Daniel Huber
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.danielhuber.me" # the base hostname & protocol for your site
twitter_username: sopleb
github_username:  vashidu
permalink: /blog/:title.html
gems: [redcarpet, jekyll-gist]
highlighter: Rouge
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
